<?php

use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');

require APPPATH . 'libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';

class Komentar extends REST_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('Komentar_model');
    }

    public function komentar_get()
    {       
        $id_thread = $this->get('id_thread');
        if($id_thread===null){
            $komentar = $this->Komentar_model->getAllKomentar();
        }else{
            $komentar = $this->Komentar_model->getAllKomentar($id_thread);
        }
        

        if($komentar){
            $this->response([
                'status' => true,
                'data' => $komentar
            ], REST_Controller::HTTP_CREATED);
        }else{
            $this->response([
                'status' => false,
                'message' => 'id not found'
            ], REST_Controller::HTTP_NOT_FOUND);
        }
        
    }


    public function komentar_post(){
        $data = [
            'id_komentar' => $this->post('id_komentar'),
            'id_thread' => $this->post('id_thread'), // Automatically generated by the model
            'username' => $this->post('username'),
            'nama_thread' => $this->post('nama_thread'),
            'isi_komentar' => $this->post('isi_komentar'),
        ];

        if($this->Komentar_model->createKomentar($data) > 0){
            $this->response([
                'status' => true,
                'message' => 'Komentar Baru Berhasil Dibuat'
            ], REST_Controller::HTTP_CREATED);
        }else{
            $this->response([
                'status' => false,
                'message' => 'failed to create'
            ], REST_Controller::HTTP_BAD_REQUEST);
        }
    }

}